config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
    
  end
  resources :tags
  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    belongs_to :author
    validates :title, presence: {message: "is required"}, length: {maximum: 230}
	validates :body, presence: {message: "is required"}, length: {maximum: 1600}
	validates :tag_list, length: {maximum: 230}
    has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
    validates_attachment_content_type :image, content_type:["image/jpg", "image/jpeg", "image/png", "image/gif"]
    
    
    def tag_list
        self.tags.collect do |tag|
			tag.name
        end.join(", ")
    end

    def tag_list=(tags_string)
        tag_names = tags_string.split(", ").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
    end

    def increment_view_count
		self.update view_count: view_count + 1
	end

end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password

  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :articles, dependent: :destroy, through: :taggings

    def to_s
        name
    end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
    belongs_to :article
    belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    include ArticlesHelper
    before_action :require_login, except: [:index, :show]

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
        @article.increment_view_count
        @comment = Comment.new
        @comment.article_id = @article.id
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end
    
	def create
        @article = Article.new(article_params)
        @article.view_count = 0
		@article.author_id = current_user.id
		@article.save
		
		flash.notice = "Article '#{@article.title}' created!"
		redirect_to article_path(@article)
	end
  
    def update
        @article = Article.find(params[:id])
        @article.update(article_params)

        flash.notice = "Article '#{@article.title}' updated!"
        redirect_to article_path(@article)
    end
   
    def destroy
        @article = Article.find(params[:id])
        

        @article.tags.each do |tag|
            if tag.taggings.count == 1
              @tag = Tag.find(tag.id)
              @tag.destroy
            end
        end
        
        @article.destroy
        flash.notice = "Article '#{@article.title}' deleted!"
        redirect_to articles_path(@articles)
    end

 end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
    def new
    end

    def create
        if login(params[:email], params[:password])
            redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
        else
            flash.now.alert = "Login failed."
            render action: :new
        end
    end

    def destroy
        logout
        redirect_to(articles_path, notice: 'Logged out!')
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]


  # def zero_authors_or_authenticated
  #   unless Author.count == 0 || current_user
  #     redirect_to root_path
  #     return false
  #   end
  #   end
    
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to authors_url, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: authors_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to authors_url, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: authors_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :require_login, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    
    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :require_login, only: [:destroy]

    def index
        @tags = Tag.all
    end
    
    def show
        @tag = Tag.find(params[:id])
    end

    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy
    
        flash.notice = "Tag '#{@tag.name}' deleted!"
    
        redirect_to action: "index"
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<tr>
  <td><p class="table-name"><%= link_to article.title, article_path(article.id), length: 130 %></p></td>
  <td><p>	<% if article.author != nil %>
  <span>by <%= article.author.username %></span>
<% end %></p></td>
  <td><p><%= article.created_at.strftime('%b %d, %Y') %></p></td>
  <td><p><%= article.comments.count %></p></td>
  <td><p><%= article.tag_list %></p></td>
  <td><p><% if logged_in? && (article.author.username == current_user.username) %><%= link_to "Edit", edit_article_path(article.id) %><% end %></p></td>
  <td><p><% if logged_in? && (article.author.username == current_user.username) %><%= link_to "Delete", article_path(article.id), method: :delete, data: {confirm: "Really delete the article?"} %><% end %></p></td>
</tr>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
    <ul>
    <% @article.errors.full_messages.each do |error| %>
        <li><%= error %></li>
    <% end %>
    </ul>
    <div class="col-md-12 text-center">
    <div class="form-group">
        <%= f.label :title %><span class="required-star">*</span>
        <%= f.text_field :title, class: "form-control", maxlength: "230", required: true %>
    </div>
    <div class="form-group">
        <%= f.label :body, "Body Text" %><span class="required-star">*</span>
        <%= f.text_area :body, class: "form-control", rows: "10", maxlength: "1600", required: true %>
    </div>
    <div class="form-group">
        <%= f.label :tag_list, "Tags: " %>
        <%= f.text_field :tag_list, placeholder: "ex: programming, rails, cooking", class: "form-control", maxlength: "230" %>
    </div>
    <div> <%= image_tag @article.image.url(:large) if @article.image.exists? %>
    </div>
    <div class="form-group">
        <%= f.label :image, "Attach an Image" %><br />
        <%= f.file_field :image, class: "btn btn-primary"%>
    </div>
    <div class="form-group">
        <a href="/articles" class="btn btn-lg btn-danger" id="cancel-button">Cancel</a>
        <%= f.submit "Create", class: "btn btn-lg btn-success", id: "submit-button" %>
  </div>
  </div>
<% end %> 

app/views/articles/edit.html.erb
<% provide(:title, "Edit Post") %> 

<div class="container">
  <h1 class="header-text">Edit Post</h1>

  <div class="row ">
    <div class="col-lg-6 mx-auto text-center">
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, "All Posts") %> 

<div class="container">
  <div class="col-xs-12">
    <h1 class="header-text">All Posts</h1><br />
  </div>

  <div class="row">
    <div class="table-responsive col-md-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Created</th>
            <th>Comments</th>
            <th>Tags</th>
          </tr>
        </thead>
        <tbody>
          <%= render @articles%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, "Create Post") %> 

<div class="container">
  <h1 class="header-text">Create Post</h1>

  <div class="row ">
    <div class="col-lg-6 mx-auto text-center">
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %> 

<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1 class="header-text"><%= @article.title %></h1>
      <% if @article.author != nil %>
        <h3>By: <%= @article.author.username %></h3>
      <% end %>
      <p>Created: <%= @article.created_at.strftime("%b %d %Y") %> [views: <%= @article.view_count %> <%= 'time'.pluralize(@article.view_count)  %>]</p>
      <br>
      <p><%= image_tag @article.image.url(:large), class: "post-image" if @article.image.exists? %></p>
      <p id="article-body"><%= @article.body %></p>
        <h4 id="tags">
          Tags:
          <% @article.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag) %>
          <% end %>
        </h4>
        <br>
          <% if logged_in? && (@article.author_id == current_user.id) %>
        <%= link_to "Edit", edit_article_path(@article) %>
        &nbsp;
        <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>
      <% end %>
    </div>

    <div class="col-md-12 mx-auto">
      <div class="col-md-6 mx-auto">
        <%= render partial: 'comments/form' %>
      </div>
      <h4>Comments (<%= @article.comments.size %>)</h4>
      <hr>
      <%= render @article.comments %>
    </div>
  </div>
  <%= link_to "<< Back", articles_path %>
</div>

app/views/author_sessions/new.html.erb
<% flash.each do |type, msg| %>
    <div class="alert alert-danger">
      <%= msg %>
    </div>
  <% end %>
<% provide(:title, "Login") %> 
<div class="container">
  <h1 class="header-text" style="margin-bottom: 25px; text-align: center;">Login</h1>
    <div class="col-md-4 mx-auto text-center">
        <%= form_tag author_sessions_path, method: :post do %>
         
   <div class="form-area">    
   <br>
        <div class="form group">
            <%= label_tag :email, "Email:" %>
            <%= text_field_tag :email%>
        </div>

        <div class="form group">
            <%= label_tag :password, "Password:" %>
            <%= password_field_tag :password%>
        </div>
    <br>
    <%= submit_tag 'Login', class: "btn btn-primary" %>
    <% end %>
    </div>
</div>
    <%= link_to '<< Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-area"> 
      <br>
      <div class="form group">
        <%= form.label :username, "Username:" %>
        <%= form.text_field :username %>
      </div>

      <div class="form group">
        <%= form.label :email, "Email:" %>
        <%= form.text_field :email %>
      </div>

      <div class="form group">
        <%= form.label :password, "Password:" %>
        <%= form.password_field :password %>
      </div>

      <div class="form group">
        <%= form.label :password_confirmation, "Password confirmation:" %>
        <%= form.password_field :password_confirmation %>
      </div>
      <br>
      <div class="actions">
      <%= submit_tag "Save",  class: "btn btn-primary" , id: "submit-button" %>
      </div>
      <% end %>
</div>

app/views/authors/edit.html.erb
<% provide(:title, "Editing Author") %> 
<div class="container">
  <h1 class="header-text" style="margin-bottom: 25px; text-align: center">Editing Author</h1>
  <div class="col-md-4 mx-auto text-center">

<%= render 'form', author: @author %>

</div>
</div>

<%= link_to '<< Back', authors_path %>

app/views/authors/index.html.erb
<% provide(:title, "Authors") %> 

<div class="container">
    <div class="col-xs-12">
      <h1 class="header-text">Authors</h1><br />
    </div>
      <div class="row">
      <table  class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Username</th>
            <th>Email</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @authors.each do |author| %>
            <tr>
              <td><%= author.username %></td>
              <td><%= author.email %></td>
              <td><p><% if logged_in? && (author.username == current_user.username) %><%= link_to "Edit", edit_author_path(author) %><% end %></p></td>
              <td><p><% if logged_in? && (author.username == current_user.username) %><%= link_to "Delete", author, method: :delete, data: { confirm: 'Are you sure?' }  %><% end %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
  </div>
</div>

<% if @authors.count == 0 %>
<span id="authors-notfound"><%= "No authors found" %></span>
<% end %>
<br>

app/views/authors/new.html.erb
<% provide(:title, "Sign Up") %> 
<div class="container">
  <h1 class="header-text" style="margin-bottom: 25px; text-align: center">Sign Up</h1>
  <div class="col-md-4 mx-auto text-center">
    <div id="signup-form">
        <%= render 'form', author: @author %>
    </div> 
  </div>
</div>
<%= link_to '<< Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>
<%= link_to '<< Authors', authors_path %> |
<%= link_to 'Edit', edit_author_path(@author) %> 

app/views/comments/_comment.html.erb
<div class="media">
  <div class="media-body">
    <h5 class="mt-0"><%= comment.author_name %> <small>Posted on <%= comment.created_at.strftime('%b %d, %Y') %></small></h5>
    <%= comment.body %>
  </div>
</div>
<br>

app/views/comments/_form.html.erb
<div id="comment-form">
  <div class="form-area"> 
    <%= form_for [ @article, @comment ] do |f| %>
      <br style="clear:both">
      <h3 style="margin-bottom: 25px; text-align: center;">Post a comment</h3>
      <div class="form-group">
        <%= f.label :author_name, "Your Name:" %>
        <%= f.text_field :author_name, class: "form-control", maxlength: "30", required: true %>
      </div>
      <div class="form-group">
        <%= f.label :body, "Comment:" %>
        <%= f.text_area :body, class: "form-control", id: "comment-text-area", maxlength: "200", rows: "2" %>
        <span class="help-block"><p id="characterLeft" class="help-block ">200 characters max</p></span>                    
      </div>
      <%= f.submit 'Submit', class: "btn btn-primary pull-right" %>
  
    <% end %>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger | <%= yield(:title) %></title>

  <!-- Meta Tags -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'  %>


</head>
<body>
<div class="container">
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Blogger</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav navbar-right ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/">All Posts</a>
        </li>
        <li class="nav-item"><% if logged_in? %>
          <a class="nav-link" href="/articles/new">Create Post</a>
        <% end %></li>
        <li class="nav-item">
          <a class="nav-link" href="/tags">Search by Tags</a>
        </li>
      <li class="nav-item"><% if logged_in? %>    
      <a class="nav-link" href="/logout", method: :get>Logout</a>     
        <% else %>
        <li><a class="nav-link" href="/login", method: :get>Login</a></li>
         <li><a class="nav-link" href="/authors/new", method: :get>Sign Up</a></li>
        <% end %>
      </li>
      </ul>
    </div>
   
  </nav>

  <p class="flash">
    <%= flash.notice %>
  </p>
  <div id="container">
    <div id="content">
  <%= yield %>
  <hr>
  <nav class="navbar navbar-dark bg-primary" id="footer">
    <div class="container">
      <div class="text-left">
        <p id="copyright">Copyright © <a href="https://github.com/MaryTalvistu" target="blank">Mary Talvistu</a>, All Rights Reserved</p>
      </div>
      <div class="text-right" id="source-code">
        <a href="https://github.com/MaryTalvistu/blogger" target="blank"><i class="fa fa-github"></i> Source Code</a>
      </div>
    </div>
  </nav>

 

  <!-- Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </div>
</body>
</html>

app/views/tags/_tag.html.erb
<tr onclick="document.location='<%= tag_path(tag.id)%>'" style="cursor: pointer;">
  <td><p class="table-name"> 
  <%= tag.name %></p></td>
  <td><p><%= tag.articles.count %></p></td>
  <td><% if logged_in? && tag.articles.count ==0 %>
  <%= link_to "Delete", tag_path(tag), method: :delete, data: {confirm: "Really delete the tag?"} %>
<% end %></td>
</tr>

app/views/tags/index.html.erb
<% provide(:title, "All Tags") %> 

<div class="container">
  <div class="col-xs-12">
    <h1 class="header-text">All Tags</h1><br />
  </div>

  <div class="row">
    <div class="table-responsive col-md-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Tag Name</th>
            <th>Article Count</th>
          </tr>
        </thead>
        <tbody>
          <%= render @tags %>
		</tbody>		
	  </table>
	  <%= link_to "<< Back", articles_path%>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<% provide(:title, @tag.name) %> 

<div class="container">
  <div class="col-xs-12">
    <h1 class="header-text">Articles Tagged with "<%= @tag.name %>"</h1><br />
  </div>

  <div class="row">
    <div class="table-responsive col-md-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Article Name</th>
            <th>Created</th>
            <th>Comments</th>
            <th>Tags</th>
          </tr>
        </thead>
        <tbody>
          <%= render @tag.articles %>
        </tbody>
      </table>
    </div>
  </div>
</div>